apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimized-baseline-nvidia-gpu-vllm-decode
spec:
  template:
    spec:
      containers:
        - name: modelserver
          env:
            # Disable NCCL tuner on GKE to work around error "Please populate NCCL_TUNER_CONFIG_PATH to use config-based tuner plugin"
            - name: NCCL_TUNER_PLUGIN
              value: "none"
            - name: NCCL_NET_PLUGIN
              value: ""
